name: 'Setup Babashka - A Clojure babushka for the grey areas of Bash.'
description: 'Setup your runner with babashka'
author: 'nha'
branding:
  icon: 'bold'
  color: 'green'
inputs:
  babashka-version:
    description: 'The babashka/babashka version to make available on the path. Only exact version allowed.'
    required: true
  babashka-url:
    description: 'The babashka/babashka url to make available on the path. Useful for CI builds. Example https://16810-201467090-gh.circle-artifacts.com/0/release/babashka-0.3.3-SNAPSHOT-linux-amd64.tar.gz When using "babashka-url" the parameter "babashka-version" is still required, to allow for appropriate caching between runs. Example: babashka-version: 0.3.3-SNAPSHOT'
  fail-on-cache-miss:
    description: 'Fail the action run if the result was not returned from the cache. Useful for tests. "true" or false otherwise'
runs:
  using: 'node20'
  main: 'dist/index.js'
